config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :informations
  resources :services, only: [:index, :show, :edit, :update]
  resources :services do
    member do
      put :validate
      put :refuse
    end
  end

  resources :products do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show, :create, :update, :destroy] do
    member do
      put :accept
      put :refuse
    end
  end

  resources :members do
    resources :services, only: [:index, :show]
  end

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  belongs_to :member
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user_id = current_user.id
    if @service.save
      return redirect_to services_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to services_path, flash: {alert: "La réservation a été modifiée avec succès"}
    else
      render :edit
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_path, status: :see_other
  end

  def validate
    @service = Service.find(params[:id])
    authorize @service, :validate?  # Utilise la méthode validate? de la politique
    if @service.update(status: "Accepté")
      redirect_to @service, notice: "La réservation a été acceptée avec succès."
    else
      redirect_to @service, alert: "La réservation n'a pas pu être acceptée."
    end
  end

  def refuse
    @service = Service.find(params[:id])
    authorize @service, :refuse?
    if @service.update(status: "Refusé")
      redirect_to @service, notice: "La réservation a été refusée avec succès."
    else
      redirect_to @service, alert: "Le refus a échoué."
    end
  end


  private

  def service_params
    params.require(:service).permit(:first_name, :last_name, :address, :phone_number, :date, :description, :user_id)
  end

end

app/views/services/edit.html.erb
<div class="card">
  <div class="card-header">
    <div class="text-header">Fiche d'information</div>
  </div>
  <div class="card-body">
    <%= simple_form_for(@service, url: service_path, method: :patch) do |f| %>
      <div>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :address %>
        <%= f.input :date %>
        <%= f.input :phone_number %>
        <%= f.input :description %>
      </div>
      <%= f.button :submit, 'Mettez à jour votre Réservation', class: 'btn-edit' %>
    <% end %>
  </div>
</div>

app/views/services/index.html.erb
<div class="mb">
  <h3>Services</h3>
  <%= link_to "Ajouter un nouveau produit", new_service_path, class: "btn_index" %>
</div>

<% @services.each do |service| %>
  <div>
  <%= link_to service_path(service) do %>
    <h2><%= service.date %></h2>
    <h2><%= service.first_name %></h2>
    <h2><%= service.last_name %></h2>
    <h2><%= service.address %></h2>
    <% end %>
  </div>
<% end %>

app/views/services/new.html.erb
<div class="card">
  <div class="card-header">
  <div class="text-header">Nouvelle Réservation</div>
    </div>
  <div class="card-body">
    <%= simple_form_for(@service, url: services_path, method: :post) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :address %>
    <%= f.input :date %>
    <%= f.input :phone_number %>
    <%= f.input :description %>


    <input type="submit" class="btn-new" value="Création d'une nouvelle réservation">
    <% end %>
  </div>
</div>

app/views/services/show.html.erb
<div class="card">
  <div class="card-header">
    <div class="card-body">
      <h1><%= @service.date %></h1>
      <p>date de la réservation: <%= @service.date %></p>
      <p>Nom du demandeur: <%= @service.last_name %></p>
      <p>prenom du demandeur: <%= @service.first_name %></p>
      <p>Adresse débrassage: <%= @service.address %></p>
      <p>numéro de téléphone: <%= @service.phone_number %></p>
      <p>Description de la demandeur: <%= @service.description %></p>

      <p>Statut de la réservation : <%= @service.status %></p>
      <% if current_user.admin? %>
        <%= button_to "Valider", validate_service_path(@service), method: :put %>
        <%= button_to "Refuser", refuse_service_path(@service), method: :put %>
      <% end %>

  <!-- création du bouton edit -->
      <div class="btn-show2">
        <%= link_to "Edit", edit_service_path(@service)%>
      </div>

<!-- bouton de supression -->
    <div class="btn-show1">
      <%= link_to "Delete",
        service_path(@service),
        data: {turbo_method: :delete, turbo_confirm: "Etes-vous sure?"}%>
    </div>