config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :informations
  resources :services, only: [:index, :show, :edit, :update]
  resources :services do
    member do
      put :validate
      put :refuse
    end
  end

  resources :products do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show, :create, :update, :destroy] do
    member do
      put :accept
      put :refuse
    end
  end

  resources :members do
    resources :services, only: [:index, :show]
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :photos
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_user!, only: [:show, :create, :new]
  include Pundit


  def index
    @products = Product.where(reserved: false)
    authorize @products
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.photos.attach(params[:product][:photos])
    authorize @product
    if @product.save
      return redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    @booking = Booking.new
    @my_product_booked = Booking.joins(:product).where("products.user_id = ?", current_user.id)
    authorize @product
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  def update
    @product = Product.find(params[:id])
    authorize @product
    if @product.update(product_params)
    redirect_to products_path(@products), flash: {alert: "Le produit a été modifié avec succès"}
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    authorize @product
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :adress, :description, :user_id, photos: [])
  end
end

app/views/products/edit.html.erb
<div class="card">
  <div class="card-header">
    <div class="text-header">Fiche d'information</div>
  </div>
  <div class="card-body">
    <%= simple_form_for(@product, url: product_path, method: :patch) do |f| %>
    <%= f.input :name %>
    <%= image_tag @product.photos.variant(resize_to_fill: [200, 200]).processed, alt: @product.name %>
      <%= f.input :adress %>
      <%= f.label :price %>
      <%= f.number_field :price %>
      <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
      <%= f.button :submit, 'Mettez à jour votre équipement', class: 'btn-edit' %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="mb">
  <h3>Produits</h3>
  <%= link_to "Ajouter un nouveau produit", new_product_path, class: "btn_index" %>
</div>
<div class="d-flex">
  <div class="row w-50">
    <% @products.each do |product| %>
      <div class="col-6 mx-auto">
        <%= link_to product_path(product) do %>
          <div class="card-category">
           <%= image_tag product.photos.variant(resize_to_fill: [200, 200]).processed, alt: product.name %>
              <p>Produit: <%= product.name %></p>
              <p>Prix: <%= product.price %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="card">
  <div class="card-header">
    <div class="text-header">Mettez en location votre équipement</div>
  </div>
  <div class="card-body">
    <%= simple_form_for(@product, url: products_path, method: :post) do |f| %>
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.input :photos, multiple: true, name: "product[photos][]" %>
      <div>
        <%= f.label :description %>
        <div class="textarea">
          <%= f.text_area :description %>
        </div>
      </div>
      <input type="submit" class="btn-new" value="Création produit">
    <% end %>
  </div>
</div>

<% if policy(Product).create? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

<% if current_user.admin? %>
  <div class="admin-message">
    <p>Message spécial pour les administrateurs : Vous avez des privilèges supplémentaires pour gérer les produits.</p>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="card">
<div class="card-header">
  <div class="card-body">
    <%= image_tag @product.photos.variant(resize_to_fill: [200, 200]).processed, alt: @product.name %>
    <h1><%= @product.name %></h1>
    <p>Prix: <%= @product.price %></p>
    <p>Description: <%= @product.description %></p>

<!--bouton réservation   -->
      <%= form_with(model: @booking, url: product_bookings_path(@product), method: :post) do |form| %>
      <%= form.hidden_field :product_id, value: @product.id %>
      <%= form.submit "Réserver", class: "btn" %>
      <% end %>

<!-- création du bouton edit -->
      <div class="btn-show2">
        <%= link_to "Edit", edit_product_path(@product)%>
      </div>

<!-- bouton de supression -->
    <div class="btn-show1">
      <%= link_to "Delete",
        product_path(@product),
        data: {turbo_method: :delete, turbo_confirm: "Etes-vous sure?"}%>
    </div>