config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :informations
  resources :services, only: [:index, :show, :edit, :update]
  resources :services do
    member do
      put :validate
      put :refuse
    end
  end

  resources :products do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show, :create, :update, :destroy] do
    member do
      put :accept
      put :refuse
    end
  end

  resources :members do
    resources :services, only: [:index, :show]
  end

end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :photo
  has_many :services

  validates :first_name, :last_name, :address, :phone_number, :email, :membership_number, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone_number, format: { with: /\A\d{10}\z/, message: "doit être un numéro à 10 chiffres" }
  validates :membership_number, numericality: { only_integer: true }
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  include Pundit

  def index
    @members = Member.all
    @bookings = Booking.all
    @services = Service.all
    authorize @members
  end

  def show
    @member = Member.find(params[:id])
    @bookings = Booking.none
    @services = Service.none
    authorize @member
  end

  def new
    @member = Member.new
    authorize @member
  end

  def create
    @member = Member.new(member_params)
    authorize @member
    if @member.save
      redirect_to members_path, notice: "L'adhérent a été créé avec succès."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @member = Member.find(params[:id])
    authorize @member
  end

  def update
    @member = Member.find(params[:id])
    authorize @member
    if @member.update(member_params)
      redirect_to members_path, notice: "L'adhérent a été mis à jour avec succès."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @member = Member.find(params[:id])
    authorize @member
    if @member.destroy
      redirect_to members_path, notice: "L'adhérent a été supprimé avec succès.", status: :see_other
    else
      redirect_to members_path, alert: "La suppression de l'adhérent a échoué."
    end
  end

  private

  def member_params
    params.require(:member).permit(:first_name, :last_name, :address, :phone_number, :email, :membership_number, :photo)
  end

  def set_user
    @user = current_user
  end
end

app/views/members/edit.html.erb
<div class="card">
  <div class="card-header">
    <div class="text-header">Modifier l'adhérent</div>
  </div>
  <div class="card-body">
    <%= simple_form_for(@member, url: member_path(@member), method: :patch, html: { class: 'form-horizontal' }) do |form| %>
      <%= form.input :first_name, label: "Prénom" %>
      <%= form.input :last_name, label: "Nom" %>
      <%= form.input :address, label: "Adresse" %>
      <%= form.input :phone_number, label: "Téléphone" %>
      <%= form.input :email %>
      <%= form.input :membership_number, label: "Numéro Adhérent" %>
      <%= form.input :date, label: "Date d'adhésion" %>
      <%= form.input :photo, label: "Photo" %>

      <%= form.button :submit, 'Mettre à jour', class: 'btn btn-edit' %>
    <% end %>
  </div>
</div>

<%= link_to 'Retour', members_path, class: 'btn btn-secondary' %>

app/views/members/index.html.erb
<h1>Liste des adhérents</h1>

<%= link_to "Ajouter un nouvel adhérent", new_member_path, class: "btn btn-primary" %>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Numéro Adhérent</th>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Adresse</th>
      <th>Téléphone</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= image_tag member.photo if member.photo.attached? %></td>
        <td><%= member.membership_number %></td>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.address %></td>
        <td><%= member.phone_number %></td>
        <td><%= member.email %></td>
        <td>
          <%= link_to 'Voir', member_path(member) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Réservations</h2>
<% if @bookings.any? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Utilisateur</th>
        <th>Produit</th>
        <th>Date</th>
        <th>Status</th> <!-- Ajout de la colonne Statut -->
        <th>Actions</th> <!-- Ajout de la colonne Actions -->
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.id %></td>
          <td><%= booking.user.email %></td>
          <td><%= booking.product.name %></td>
          <td><%= booking.date %></td>
          <td>
            <strong>Status de la réservation:</strong>
            <%= booking.accepted.nil? ? "En attente" : (booking.accepted ? "Acceptée" : "Refusée") %>
          </td>
          <td>
            <%= link_to "Voir la réservation", booking_path(booking) %>
            <!-- Ajouter d'autres actions si nécessaire -->
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Aucune réservation trouvée.</p>
<% end %>

<h2>Services</h2>
<% if @services.any? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Utilisateur</th>
        <th>Service</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.id %></td>
          <td><%= service.user.email %></td>
          <td><%= service.first_name %></td>
          <td><%= service.last_name %></td>
          <td><%= service.address %></td>
          <td><%= service.phone_number %></td>
          <td><%= service.date %></td>
          <td><%= link_to "voir la demande de réservation", service_path(service), class: "btn_index" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Aucun service trouvé.</p>
<% end %>

app/views/members/new.html.erb
<%= simple_form_for @member do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :email %>
  <%= f.input :membership_number %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/members/show.html.erb
<h1><%= @member.first_name %> <%= @member.last_name %></h1>

<% if @member.photo.attached? %>
  <%= image_tag @member.photo %>
<% end %>

<p><strong>Adresse:</strong> <%= @member.address %></p>
<p><strong>Téléphone:</strong> <%= @member.phone_number %></p>
<p><strong>Email:</strong> <%= @member.email %></p>
<p><strong>Numéro Adhérent:</strong> <%= @member.membership_number %></p>

<%= link_to 'Modifier', edit_member_path(@member) %>
<%= form_with model: @member, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet adhérent ?' }, class: 'inline-form' do %>
  <%= submit_tag 'Supprimer' %>
<% end %>

<h2>Réservations</h2>
<% if @bookings.any? %>
  <% @bookings.each do |booking| %>
    <p><strong>Produit:</strong> <%= booking.product.name %> - <strong>Date:</strong> <%= booking.date %></p>
  <% end %>
<% else %>
  <p>Aucune réservation trouvée.</p>
<% end %>

<h2>Services</h2>
<% if @services.any? %>
  <% @services.each do |service| %>
    <p><strong>Service:</strong> <%= service.name %> - <strong>Date:</strong> <%= service.date %></p>
  <% end %>
<% else %>
  <p>Aucun service trouvé.</p>
<% end %>